[package]
name = "meaupdater"
version = "0.4.0-beta"
edition = "2024"

[dependencies]
anyhow = "1.0"
gtk = { version = "0.8", package = "gtk4" }
gio = "0.19"
glib = "0.19"
pango = "0.19"
gdk-pixbuf = "0.19"
open = "5.0"
